# Generated by Django 4.2.16 on 2024-10-13 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('teams', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='personnel',
            field=models.ManyToManyField(blank=True, related_name='team_members', to='users.personnel'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_type',
            field=models.CharField(choices=[('wing', 'Wing Team'), ('fuselage', 'Fuselage Team'), ('tail', 'Tail Team'), ('avionics', 'Avionics Team'), ('assembly', 'Assembly Team')], max_length=20),
        ),
    ]
