# Generated by Django 4.2.16 on 2024-10-12 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft_type', models.CharField(choices=[('tb2', 'TB2'), ('tb3', 'TB3'), ('akinci', 'AKINCI'), ('kizilelma', 'KIZILELMA')], max_length=20)),
                ('assembled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
