# Generated by Django 4.2.16 on 2024-10-12 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aircrafts', '0001_initial'),
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='avionics',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avionics', to='parts.part'),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='fuselage',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuselage', to='parts.part'),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='tail',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tail', to='parts.part'),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='wing',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wing', to='parts.part'),
        ),
    ]
