# Generated by Django 4.2.16 on 2024-10-13 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_initial'),
        ('aircrafts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='avionics',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avionics', to='parts.part'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='fuselage',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuselage', to='parts.part'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='tail',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tail', to='parts.part'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='wing',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wing', to='parts.part'),
        ),
    ]
